#!/usr/bin/env python

import sys
import json
import datetime

def check(instream):
    input = json.load(instream)

    new_version = input['source']['bucket']

    now = datetime.datetime.now()
    return [{"Bucket": u"%s %s" % (new_version, now) }]

def main():
    print(json.dumps(check(sys.stdin)))

if __name__ == '__main__':
    main()
