#!/usr/bin/env python

import sys
import json
import datetime

def check(instream):
    input = json.load(instream)

    new_version = ""

    if (input["version"] is None):
        new_version = "mysql"
    
    return [{"Version": u"%s" % (new_version) }] if len(new_version) > 0 else []

def main():
    print(json.dumps(check(sys.stdin)))

if __name__ == '__main__':
    main()
