#!/usr/bin/env python

import sys
import json

from os import path

def check(instream):
    input = json.load(instream)

    new_version = ""
    
    payload = {
        "version" : {
            "Version" : u"%s" % (new_version)
        },
        "metadata" : [
            { "name": "Version", "value": new_version }
        ]
    }

    return payload

def main():
    print(json.dumps(check(sys.stdin)))

if __name__ == '__main__':
    main()
