#!/usr/bin/env python

import sys
import json

from os import path
from artifact_manager.parser import build_upload_path, get_upload_targets
from artifact_manager.driver import s3

def check(instream):
    input = json.load(instream)

    upload_path = build_upload_path(sys.argv[1], input)
    upload_targets = get_upload_targets(sys.argv[1], input)

    s3_session = s3(input['source']['access_key'],input['source']['secret_access_key'])
    for target in upload_targets:
        data = open(target['path'], 'rb')
        s3_session.s3_upload(input['source']['bucket'], data, path.join(upload_path, target['filename']))

    payload = {
        "version" : {
            "Upload Path" : u"%s" % (upload_path)
        },
        "metadata" : [
            { "name": "Upload Path", "value": str(path.join(input['source']['bucket'], upload_path)) }
        ]
    }

    return payload

def main():
    print(json.dumps(check(sys.stdin)))

if __name__ == '__main__':
    main()
